import React from 'react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, PieChart, Pie, Cell, BarChart, Bar } from 'recharts';
import { UserPlus, Building2, ReceiptText, FileText, CheckCircle2 } from 'lucide-react';

export function StatCard({title,value,sub,i}){return <div className="stat"><div><p>{title}</p><h2>{value}</h2><small>{sub}</small></div><div className="stat-icon">{i%2?<Building2/>:<UserPlus/>}</div></div>}
export function Panel({title,children,action='View All'}){return <section className="panel"><div className="panel-head"><h3>{title}</h3><a>{action}</a></div>{children}</section>}
export function LinePanel(){const d=['Jan','Feb','Mar','Apr','May','Jun'].map((m,i)=>({m,v:120+i*82})); return <Panel title="Employee Overview"><div className="chart"><ResponsiveContainer><LineChart data={d}><XAxis dataKey="m"/><YAxis/><Tooltip/><Line type="monotone" dataKey="v" stroke="currentColor" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Panel>}
export function PiePanel({title='Employee by Department'}){const d=[{name:'Development',value:220},{name:'HR',value:80},{name:'Marketing',value:60},{name:'Sales',value:90},{name:'Support',value:74}]; return <Panel title={title}><div className="pie-wrap"><ResponsiveContainer width="48%" height={170}><PieChart><Pie data={d} dataKey="value" innerRadius={45} outerRadius={75}>{d.map((_,i)=><Cell key={i}/>)}</Pie></PieChart></ResponsiveContainer><div className="legend">{d.map(x=><p key={x.name}><span/> {x.name}<b>{x.value}</b></p>)}</div></div></Panel>}
export function ProgressPanel(){const d=['ERP System','Mobile App','Website Redesign','CRM Integration','Data Migration'].map((m,i)=>({m,v:[75,60,90,40,70][i]})); return <Panel title="Project Progress"><div className="chart"><ResponsiveContainer><BarChart data={d} layout="vertical"><XAxis type="number"/><YAxis dataKey="m" type="category" width={105}/><Tooltip/><Bar dataKey="v" fill="currentColor" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></div></Panel>}
export function TablePanel({title='Recent Employees'}){const rows=['John Doe','Priya Patel','Amit Kumar','Neha Singh'].map((n,i)=>[n,`EMP00${i+1}`,['Development','HR','Marketing','Testing'][i],['Active','Pending','Approved','Online'][i]]); return <Panel title={title}><table><thead><tr><th>Name</th><th>ID</th><th>Department</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map((c,i)=><td key={i}><span className={i===3?'badge':''}>{c}</span></td>)}</tr>)}</tbody></table></Panel>}
export function TaskList(){return <Panel title="My Team Tasks"><div className="list">{['Review Project Report','Client Meeting','Update Documentation','Code Review'].map((t,i)=><div className="list-row" key={t}><CheckCircle2 size={16}/><b>{t}</b><span className={`priority p${i}`}>{['High','Medium','Medium','Low'][i]}</span><small>Due {25+i} May</small></div>)}</div></Panel>}
export function QuickActions(){const a=[['Add Employee',UserPlus],['Add Department',Building2],['Generate Payroll',ReceiptText],['View Reports',FileText]]; return <Panel title="Quick Actions" action=""><div className="quick">{a.map(([t,Icon])=><button key={t}><Icon/><span>{t}</span></button>)}</div></Panel>}
